### ISSUE TITLE
Not an issue but want to connect!

### ISSUE THREAD

**Issue by t8** [bitruss/awesome-arweave#4]
Hey! 

Hope you're doing well. Apologies to bother here but just want to say that this list is incredible.

Would love to connect at some point soon if you see this! Feel free to shoot me an email (tate@verto.exchange) or Discord (@tate#5885).

Again, really really cool!

**Comment by bitruss** [comment]
The following is my Contact:

Email(zion@meson.network)
Discord(@zionfuo#8469)
Telegram(@zionfuo)
